### DISCUSSION TITLE
use config-settings for package settings

### DISCUSSION THREAD

**Discussion by minrk** [scikit-build/scikit-build-core#1468] [Q&A]
PEP 517 config-settings are used to set build-backend inputs, and can be used to set cmake variables with `-C cmake.define.NAME`. Is it possible (or advisable) to be able to register my own config-settings keys for my package and have them available in cmake? Or are config-settings really meant to be only for the build system itself, not for the package being built?

I can (and do) use CMake defines for the inputs I want, but for a user-facing documentation of these options, I'd rather have my own settings so that I can have a Python-standard interface for configuring pyzmq builds, independent of the underlying build implementation. So e.g. if I switched to a different underlyingsetup, user install commands wouldn't need to change. I have this already with environment variables, but it would be nice if I could migrate to PEP 517 args e.g. `-C zmq.libzmq="bundled"`. Is this something that is possible with scikit-build-core and/or something worth pursuing? As it stands, I think `export ZMQ_PREFIX=/foo` is a _better_ interface/experience than `-C cmake.define.ZMQ_PREFIX=/foo`, because it will still work if I try out meson, etc. (and indeed still works the same with cmake as it did with setuptools).

**Comment by henryiii** [comment]
I believe we discussed ideas for this in a community meeting a while back. It was around the time we got `if.env.<VAR>`, which allows you to set up an override via an environment variable. It was just a bit lower priority, since it takes more design. It also won't work with setuptools and hatching plugins.

As a rough draft (not looking up the old discussion since I don't think it went very far), maybe it would look something like this:

```toml
[tool.scikit-build.config-setting]
"zmq.prefix" = {type = "str", help = "Location"}
"zmq.libzmq" = {type = "str", help = "Can be bundled"}

[tool.scikit-build.define]
ZMQ_PREFIX = {config-setting = "zmq.prefix"}
ZMQ_LIBZMQ = "OFF"

[[tool.scikit-build.overrides]]
if.config-setting."zmq.libzmq" = "bundled"
messages.after-success = "{green}Using bundled libzmq"
define.ZMQ_LIBZMQ = "ON"
```

**Reply by minrk** [reply]
Thanks. I think I was thinking of something a little simpler, like just making the dict itself accessible somehow at build time, rather than letting me do mapping of config->cmake in pyproject.toml. More of a passthrough type deal, leave it up to my CMakeLists to interpret, but "they're here when cmake runs, if you want them."

If it's only going to work in skbuild, it misses much of the point for me. Since env variables already work fine across the transition from setuptools to skbuild, I'll stick to them in docs. Package-defined options doesn't seem to be what the pep517 config-settings are for, I just thought they might be.

**Reply by henryiii** [reply]
Other tools like meson-python can't define custom config-settings at the moment. And setuptools' implementation of config-settings is unusable for its own settings, much less custom ones. :)

**Reply by henryiii** [reply]
Above,

```toml
[tool.scikit-build.config-setting]
"zmq.prefix" = {type = "str", help = "Location"}

[tool.scikit-build.define]
ZMQ_PREFIX = {config-setting = "zmq.prefix"}
```

Would be a passthrough.
