### DISCUSSION TITLE
Point scikit-build-core towards a subdirectory when building

### DISCUSSION THREAD

**Discussion by JackAshwell11** [scikit-build/scikit-build-core#1469] [Q&A] [answered]
I have a project structure like this:
```
root
├─ src
│   ├─ py
│   │   ├── run.py
│   └─ ext
│       ├── main.cpp
│       ├── CMakeLists.txt
│       └── CMakePresets.json
├── pyproject.toml
```
How would I go about structuring the pyproject so that scikit-build-core builds the `ext` project.

**Comment by henryiii** [comment]
```toml
[tool.scikit-build]
cmake.source-dir = "src/ext"
wheel.packages = ["src/py"]
```

If your project is named `py`, you don't need the final line above.

**Reply by JackAshwell11** [reply, marked as answer]
This works now, thanks. Also if my CMake project used presets and a dependency manager like vcpkg (which requires triplets for each platform), how would I specify the preset to use. I've currently got, but it doesn't seem to be working:
```taml
[[tool.scikit-build.overrides]]
if.platform-system = "$win32"
cmake.args = [ "--preset WinRelease"]

[[tool.scikit-build.overrides]]
if.platform-system = "$linux"
cmake.args = ["--preset LinuxRelease"]
```

**Reply by henryiii** [reply]
`cmake.args = [ "--preset", "WinRelease"]` perhaps?

**Reply by JackAshwell11** [reply]
That would work on windows, but on Linux, it would need `LinuxRelease`

**Reply by henryiii** [reply]
No, I meant

```toml
[[tool.scikit-build.overrides]]
if.platform-system = "^win32"
cmake.args = [ "--preset", "WinRelease"]

[[tool.scikit-build.overrides]]
if.platform-system = "^linux"
cmake.args = ["--preset", "LinuxRelease"]
```

**Reply by henryiii** [reply]
Ahh, it’s '^', not '$'.

**Reply by henryiii** [reply]
Fixing the typo in the docs in https://github.com/scikit-build/scikit-build-core/pull/879

**Reply by JackAshwell11** [reply]
This works great, thanks a lot!

**Reply by JackAshwell11** [reply]
So I am getting another problem now which is only happening in CI and it seems to be because of my introduction of scikit-build-core. The CI run: https://github.com/JackAshwell11/Hades/actions/runs/10617259955/job/29429625732?pr=236

My `pyproject.toml` changes are just:
```toml
[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

...

[tool.scikit-build]
cmake.source-dir = "src/hades_extensions"

[[tool.scikit-build.overrides]]
if.platform-system = "^win32"
cmake.args = ["-DDO_TESTS=OFF", "--preset WinRelease"]

[[tool.scikit-build.overrides]]
if.platform-system = "^linux"
cmake.args = ["-DDO_TESTS=OFF", "--preset LinuxRelease"]
```

And the changes to my `CMakeLists.txt`:
```cmake
pybind11_add_module(${PY_MODULE} ${CMAKE_SOURCE_DIR}/src/binding.cpp)
target_link_libraries(${PY_MODULE} PRIVATE ${CPP_LIB})
install(TARGETS ${PY_MODULE} LIBRARY DESTINATION .)
get_target_property(CHIPMUNK_DLL unofficial::chipmunk::chipmunk LOCATION)
install(FILES ${CHIPMUNK_DLL} DESTINATION .)
```

This all works locally and the CI actions do correctly install MSVC and CMake so I'm not entirely sure why its saying this:
```
      CMake Error at CMakeLists.txt:20 (project):

        Generator Ninja does not support platform specification, but platform x64 was specified.
```

EDIT: Adding `-DCMAKE_GENERATOR_PLATFORM=` to `cmake.args` does fix this, not sure why this argument is passed to CMake though:
```toml
[[tool.scikit-build.overrides]]
if.platform-system = "^win32"
cmake.args = ["-DCMAKE_GENERATOR_PLATFORM=", "-DDO_TESTS=OFF", "--preset WinRelease"]

[[tool.scikit-build.overrides]]
if.platform-system = "^linux"
cmake.args = ["-DCMAKE_GENERATOR_PLATFORM=", "-DDO_TESTS=OFF", "--preset LinuxRelease"]
```
