### DISCUSSION TITLE
Does scikit-build support compilers other than msvc on windows?

### DISCUSSION THREAD

**Discussion by xsxszab** [scikit-build/scikit-build-core#1472] [Q&A]
In one of my projects, I need to use `icx` (from Intel oneAPI) as the C++ compiler when building with pip. I’m using the following command:
```bash
set "CMAKE_ARGS=-DCMAKE_CXX_COMPILER=icx" && pip install .
```
For reference, my project uses `scikit-build` as the build backend, configured as follows in `pyproject.toml`:
```toml
[build-system]
requires = ["scikit-build-core", "setuptools>=64.0"]
build-backend = "scikit_build_core.build"
```
However, during compilation, `pip` always defaults to using MSVC as the compiler, ignoring the `CMAKE_ARGS` environment variable I set.

In contrast, when I build the C++ portion of the project directly using `cmake`, it correctly picks `icx` as expected:
```bash
cmake -B build -DCMAKE_CXX_COMPILER=icx
cmake --build build
```
This works without any issues.

My question is: Does this behavior imply that scikit-build is hardcoded to use MSVC on Windows?  If so, is there a way to override this behavior?
