### DISCUSSION TITLE
Excluding 3rd party C++ deps (such as Eigen) from python packages

### DISCUSSION THREAD

**Discussion by phaedon** [scikit-build/scikit-build-core#1473] [Q&A]
We have a project which wraps some C++ libraries using pybind11 and then packages them in a wheel for installation, locally or in a Docker image.

I'm trying to migrate our old setup.py configs to `scikit_build_core`
However, I see that a large number of 3rd party deps (primarily Eigen) are getting packaged and installed into the wheel.

Note that we are pulling in these deps using CMake's `FetchContent_Declare` and `FetchContent_MakeAvailable`. The default then is to pull them all into the `build-*/_deps/` subdir. However, when I run the build from the python command below, they are apparently fetched into some temporary build directory, from which they are "installed" into a platlib directory such as  `/tmp/tmpu3ectkwi/wheel/platlib/include/eigen3/unsupported/`

In this excerpt, is there something I'm doing wrong with my configuration? I've studied the example at https://github.com/pybind/scikit_build_example but this is quite minimal and doesn't address the question of third-party libraries.

```toml
[tool.scikit-build]
cmake.source-dir = "../.."
build.targets = ["our_pybind_cmake_target"]
build.verbose = true
sdist.cmake = true
wheel.cmake = true
wheel.packages = ["our_package_name"]
wheel.exclude = ["**/include/**", "wheel/platlib/**"]
```

Am running this from the command line as follows:
`python -m build --wheel  --sdist --verbose`
