### ISSUE TITLE
How to skip cmake building via pip command

### ISSUE THREAD

**Issue by Roy-Kid** [scikit-build/scikit-build-core#1039]
Hi, I want to skip the CMake build when deploying my project's documentation through an integration process like Cloudflare Pages. I don’t want the deployment process to install my project—only the dependencies specified in `optional.doc`. However, it seems that `--no-deps` only skips dependency installation, not the CMake build. I’d prefer not to use a `requirements-doc.txt` file. Is there a way to skip the CMake build directly in the `pip` command?

**Comment by LecrisUT** [comment]
Dependency groups from [`PEP 735`](https://peps.python.org/pep-0735/) is the recommended way forward, but I am not sure how much the doc builders are compatible with it. `pip` and `uv` should be compatible, or at least in the next release.

Alternatively, you can add something like
```toml
# Do not build library on documentation builders
[[tool.scikit-build.overrides]]
if.any.env.READTHEDOCS = true
if.any.env.BUILD_DOCS = true
wheel.cmake = false
```

Note that that would also skip docstrings from inside the compiled files, but probably you do not have meaningful ones built in there?
