### ISSUE TITLE
sdist.include can not work

### ISSUE THREAD

**Issue by ChaoII** [scikit-build/scikit-build-core#1105]
If I don’t specify sdist.include, the source distribution includes only the default files and directories, and it correctly respects the `.gitignore` file.
However, once I override `sdist.include`, the source distribution ends up including everything in the project directory — even files and folders that should normally be excluded.
Even when I set `sdist.include = ["csrc"]`, the resulting source distribution still contains all files and directories from the current working directory where I run `python -m build --sdist`

**Comment by ChaoII** [comment]
> I'm going to rework file inclusion/exclusion in 0.12, [#1048](https://github.com/scikit-build/scikit-build-core/pull/1048) is on hold for that. I plan to make a quick patch release soon (for the increased speed on large directory trees we got recently) then start on 0.12, there are quite a few open PRs that are targeting 0.12.
> 
> Debug logging should explain exactly what it's doing.
> 
> Could you try `sdist.include = ["/csrc"]`? Unless you mean you want excluded files inside `/csrc` to not show up - `include` overrides `exclude` in the current system.

It's my directory tree
![Image](https://github.com/user-attachments/assets/d73f9f30-d5f1-4796-bf60-0b3119caf4d8)

```toml
wheel.packages = ["python/modeldeploy"]

#sdist.exclude = [
#    ".github",
#    "csharp",
#    "examples",
#    "tests",
#    "capi",
#]

sdist.exclude = [
    "./csrc",
]
```
When I execute `python -m build --sdist` commond，other directories and files  are contained in the tar.

![Image](https://github.com/user-attachments/assets/8a80ae6f-0dbd-4e8a-92c5-4467390b2e5b)
