### ISSUE TITLE
Specifying cmake to place built binaries on PATH from pyproject.toml

### ISSUE THREAD

**Issue by Zeitsperre** [scikit-build/scikit-build-core#194]
I just happened upon this library today, and I am finding it to be a fantastic option for modernizing some projects based on `setuptools`. Great stuff. I'm not very familiar with Python build back-ends, so feel free to close if this is off-topic.

The use-case I have that I'm trying to hack my way through is how I can install a cmake-built binary/executable on the `PATH` that my Python library relies upon and makes calls to via console commands.

My ideal solution would be for the `pip install` step to compile my executable using cmake, then install it into either my global "/bin" (if called with root privileges) or my python environment's `/bin` (e.g. `/home/me/Anaconda/envs/my_env/bin`). Meanwhile, the Python wheel would be installed as usual (under site-packages).

I'm wondering how I can specify from `pyproject.toml` to make this location dynamic based on the environment (i.e. if I want to support multiplatform/multiOS).

Currently, the only way I have this working is by hard-coding paths (BIN_DIR):

`pyproject.toml`:

```toml
[build-system]
requires = ["scikit_build_core"]
build-backend = "scikit_build_core.build"

[project]
name = "MyPythonLibrary"
version = "0.0.1"
requires-python = ">=3.8"

[tool.scikit-build]
cmake.minimum-version = "3.20"
cmake.build-type = "Release"
cmake.args = [
    "-DCMAKE_CXX_FLAGS='-Dnetcdf -Wno-deprecated'",
]
cmake.verbose = true

[tool.scikit-build.cmake.define]
FIND_NETCDF_PATH = "/build_scripts"
BIN_DIR = "/home/me/Anaconda/envs/skbuild_test/bin"
```

`CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.20)

# Setup Project
PROJECT(MyBinary CXX)

# Find NetCDF
list(APPEND CMAKE_MODULE_PATH ${FIND_NETCDF_PATH})
find_package(NetCDF REQUIRED)

# find header & source
file(GLOB HEADER "src/*.h")
file(GLOB SOURCE "src/*.cpp")

add_executable(MyBinary
  ${SOURCE}
  ${HEADER}
)

source_group("Header Files" FILES ${HEADER})
source_group("Source Files" FILES ${SOURCE})

target_link_libraries(MyBinary PRIVATE NetCDF::NetCDF)
target_compile_features(MyBinary PUBLIC cxx_std_11)
set_target_properties(MyBinary PROPERTIES LINKER_LANGUAGE CXX)

install(TARGETS MyBinary DESTINATION ${BIN_DIR})
```

Thanks!
