### ISSUE TITLE
Doc: Adding `_version.py` files to `sdist.include`

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#274]
How do we exclude the `_version.pyi` file and include the `_version.py` file? I guess we need the equivalent of `hatch.build.hooks.vcs.version-file`?

Also need a similar path fixing for editable installs.

**Comment by henryiii** [comment]
You don't want to exclude `.pyi` files, those should be in the package. The default template doesn't have typing information in it.

If `_version.py` is in your `.gitignore` (and it should be), then you'll want:

```toml
[tool.setuptools_scm]
write_to = "pkg/_version.py"

[tool.scikit-build]
sdist.include = "pkg/_version.py"
```
