### ISSUE TITLE
Dynamic metadata: entry-points possible?

### ISSUE THREAD

**Issue by bilke** [scikit-build/scikit-build-core#296]
Are other dynamic metadata than version and readme possible with scikit-build-core?

The following did not work for me (no error but also no console entry point generated):

```toml
[project]
...
dynamic = ["version", "entry-points"]

[tool.setuptools.dynamic]
entry-points = { file = "entry_points.txt" }
```

```ini
[console_scripts]
mycmd = mycmd:main
```

Or do we need to implement this as a plugin similar to version and readme?

Thanks!
