### ISSUE TITLE
feat: Overrides mechanism

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build-core#332]
This is an initial idea for the overrides system.

The overrides array would requires the `select` key set:

```toml
[[tool.scikit-build.overides]]
select = {python-version=">=3.8", implementation-name="cpython"}
```

The keys would be based on [PEP 508](https://peps.python.org/pep-0508/#environment-markers):

* `python-version`: a SpecifierSet that matches the Python version (note: PEP 508 splits this into `python_full_version`, maybe we should too, and make them mutually exclusive)
* `implementation-name`
* `implementation-version`
* `platform-system`
* `platform-machine`

The other values (besides `python-version`) would support regular expressions.

All other values in that array entry are then used over the original values if the select matches. Table/array merging should be considered, but might not make it in the first version. At least one value is required.

**Comment by henryiii** [comment]
This will still come somewhat soon, but the key reason I was going to prioritize it (and some cleanup in preparation has already gone into 0.4.2) was for conditional limited API / stable ABI, but we were able to support that naturally without overrides by using the value (`cp312` only affect 3.12+, for example). So this might be bumped down in priority for a bit.

**Comment by LecrisUT** [comment]
Is the naming convention of `select` standardized? I find it a bit unintuitive. I like [this syntax](https://fmf.readthedocs.io/en/stable/features.html#adjust) more and I think ansible uses something similar. Specifically an `if`, `when` verb would be more intuitive.

Also unclear how you would add more than one overrides

**Comment by henryiii** [comment]
It's not set in stone. It's based on mypy:

```toml
[[tool.mypy.overrides]]
module = 'packagename'
...
```

And cibuildwheel:

```toml
[[tool.mypy.overrides]]
select = 'cp*'
...
```

Though it's not really the same as either one. "module" is what you are matching against, and "select" sort of is (it's matched against "selectors" in cibuildwheel terms).

```toml
[[tool.scikit-build.overrides]]
if = {python-version=">=3.10"}
...
```

You can also write it:

```toml
[[tool.scikit-build.overrides]]
if.python-version=">=3.10"
```

I rather like `if`, since it's a Python keyword, it would be unlikely to collide with future config options. It also feels more Pythonic to me than `when`.
