### ISSUE TITLE
version file is not generated with setuptools-scm 8

### ISSUE THREAD

**Issue by njzjz** [scikit-build/scikit-build-core#507]
Today [setuptools-scm](https://github.com/pypa/setuptools_scm/releases) released v8.0.0 and v8.0.1. After that, the version file is not generated anymore.

```toml
[tool.setuptools_scm]
write_to = "deepmd/_version.py"
```

However, there is no issue when using setuptools.
