### ISSUE TITLE
Possibly have an auto package dir, `package` or `src/package`, settable config?

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build-core#51]
Still waiting on the settable config. Plan:

```toml
# Include these files even if excluded
wheel.artifacts = ["..."]

# Force just these files in the output
wheel.only-include = ["a/b"]

# Copy, stripping all but the last name
# If not given, default to "src/<package>", "<package>" (taking first found)
wheel.packages = ["src/foo"]

[tool.scikit-build.wheel.sources]
"src/foo" = "bar"
# OR:
sources = ["src"]

# ? tool.scikit-build.force-include
```

(Some random thoughts from https://hatch.pypa.io/latest/config/build above)
