### ISSUE TITLE
Python Language Server not finding package

### ISSUE THREAD

**Issue by drisspg** [scikit-build/scikit-build-core#658]
# Summary

I haven't been able to figure this one out, curious if other have seen it.

If I create a python project and use hatchling as the build system:
```Toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```
When I install this package in editable mode to an env, select that env with vscode everything works as expected.

When I use scikit-build-core the lsp doesn't seem to find the package unless I do 
``` Python
from my_package.my_package import ...
```

Sorry if this question is better suited for the python LSP server but curious if others have ran into this, and maybe there is a build setting I need to use
