### ISSUE TITLE
Difficulty Packaging Scripts Folder with scikit-build-core

### ISSUE THREAD

**Issue by ahnaf-tahmid-chowdhury** [scikit-build/scikit-build-core#667]
### Description
I am currently in the process of migrating from `scikit-build` to `scikit-build-core` for packaging my project, specifically the PyNE repository. Previously, with `scikit-build`, I utilized a method to package the `scripts` folder containing all the executables. However, I am encountering difficulty replicating this functionality with `scikit-build-core`.

### Steps to Reproduce
1. Attempt to package the `scripts` folder containing executables using `scikit-build-core`.
2. Encounter issues due to differences in methods or functionality between `scikit-build` and `scikit-build-core`.
3. Unable to find a suitable alternative or workaround within the documentation or resources available.

### Expected Behavior
I expect to be able to package the `scripts` folder containing executables seamlessly using `scikit-build-core`, similar to how it was done with `scikit-build`.

### Current Approach
Here's the method I was using previously with `scikit-build`:

```python
# Collect scripts
scripts = [os.path.join("scripts", f) for f in os.listdir("scripts")]
scripts = [
    s
    for s in scripts
    if (os.name == "nt" and s.endswith(".bat"))
    or (os.name != "nt" and not s.endswith(".bat"))
]

# Collect extension
extension = ["*.dll", "*.so", "*.dylib", "*.pyd", "*.pyo"]

# Setup configuration
setup(
    packages=[
        "pyne",
        "pyne.dbgen",
        "pyne.apigen",
        "pyne.xs",
        "pyne.transmute",
        "pyne.gui",
        "pyne.cli",
        "pyne.fortranformat",
    ],
    package_data={
        "lib": extension,
        "pyne": [
            "*.pxd",
            "*.json",
            "*.inp",
        ]
        + extension,
        "pyne.xs": ["*.pxd"] + extension,
        "pyne.gui": ["*.pyw"],
        "pyne.dbgen": ["*.html", "*.csv", "abundances.txt", "mass.mas16", "*.dat"],
    },
    scripts=scripts,
    cmake_args=cmake_args,
    cmake_install_dir=".",
)
```

### Additional Information

- Using `scikit-build-core` version 0.8.2.
- Repository: [PyNE with scikit-build-core](https://github.com/pyne/pyne/tree/scikit-build-core)
- Repository: [PyNE with scikit-build](https://github.com/pyne/pyne/tree/scikit-build)
- Any insights, guidance, or examples on how to achieve similar packaging of the `scripts` folder with `scikit-build-core` would be greatly appreciated.

**Comment by henryiii** [comment]
You can write to `SKBUILD_SCRIPTS_DIR` from CMake. https://scikit-build-core.readthedocs.io/en/latest/cmakelists.html#install-directories

**Comment by LecrisUT** [comment]
I am wondering if OP means static (shell-like) scripts. But I guess in that case as well, you can add a `install()` to copy those withing CMake.

> You can write to `SKBUILD_SCRIPTS_DIR`

Worth aliasing `SKBUILD_BIN_DIR` to it as well, to mimic `GnuInstalldir`?

**Comment by ahnaf-tahmid-chowdhury** [comment]
Here is my new `pyproject.toml` that I am currently working on

```toml
[build-system]
requires = [
    "scikit-build-core",
    "cython<3",
    "numpy",
]
build-backend = "scikit_build_core.build"

# Project Metadata
[project]
name = "pyne-toolkit"
dynamic = ["version"]
authors = [{ name = "PyNE Team", email = "pyne-dev@googlegroups.com" }]
license = { file = "license.txt" }
description = "PyNE: The Nuclear Engineering Toolkit"
readme = "readme.rst"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.8"
dependencies = [
    "progress",
    "tables",
    "numpy",
    "scipy",
    "matplotlib",
    "jinja2",
    "future",
]

# Optional Dependencies
[project.optional-dependencies]
test = ["pytest"]
docs = ["sphinx"]

# Project URLs
[project.urls]
"Homepage" = "https://pyne.io"
"Bug Tracker" = "https://github.com/pyne/pyne/issues"
"Source Code" = "https://github.com/pyne/pyne"

# Scikit-Build Configuration
[tool.scikit-build]
cmake.verbose = true
logging.level = "INFO"
wheel.packages = ["pyne"]
wheel.exclude = ["CMakeLists.txt", "*.pyx"]

# Get version from CMakeLists
[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.setuptools_scm"

[tool.setuptools_scm]

# Add the version to the package
[[tool.scikit-build.generate]]
path = "pyne/_version.py"
template = '''
__version__ = "${version}"
'''

# Add the version to the header
[[tool.scikit-build.generate]]
path = "src/pyne_version.h"
location = "source"
template = '''
#ifndef PYNE_VERSION_HEADER
#define PYNE_VERSION_HEADER

#define PYNE_VERSION "${version}"

#endif // PYNE_VERSION_HEADER
'''
```

It appears that I'm unable to configure the scripts from this toml file and must handle this from the CMake side.

Lately, I've observed that whenever I install a wheel, it places everything into the site-packages directory, including the include, lib, and share directories. Is this behavior a result of using scikit-build-core? I prefer them to be installed into the environment directory as it's more neutral.
