### ISSUE TITLE
Extra wheel directories

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build-core#67]
Idea:

Have a configuration option that allows the install directory to be controlled.

```toml
[tool.scikit-build]
wheel.install_dir = "." # default
wheel.install_dir = "packagename" # Can be a relative dir
wheel.install_dir = "/platlib" # EXPERIMENTAL! Requires flag to activate.
```

There could be variables for all the dirs:

```cmake
${SKBUILD_PLATLIB_DIR}
${SKBUILD_DATA_DIR}
${SKBUILD_HEADERS_DIR}
${SKBUILD_SCRIPTS_DIR}
```
(Maybe scripts too?)
