### ISSUE TITLE
Running from python less than ABI3 should build classic wheels

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build-core#69]
Also should think about the name (maybe `api-abi`, or maybe we could just take the `api`).

Idea: These are both properties of the wheel building step

```toml
[tool.scikit-build]
wheel.api = "cp38"
wheel.expand-macos-universal = true
```

We could add `wheel.abi` later only if it's needed. I liked the readability of `py3-none`, but really `py3` is still rather obviously not Python dependent.
