### ISSUE TITLE
Add system for adding defines

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build-core#71]
Maybe we could drop the `scikit-build` prefix (possibly optionally?)? In that case, maybe `define` or `cmake-define` or `cmake.define` (which isn't how I've been using `cmake.` exactly?) would be better?

Actually, I'm liking that:

```toml
[tool.scikit-build.cmake.define]
SOME_THING = "thing"
```

```bash
-Dcmake.define.SOME_THING="thing"
```

Previous idea: ~~Possibly:~~

```toml
[tool.scikit-build.D]
SOME_THING = "thing"
```

~~Which would be quite nice on the command line: `-Cscikit-build.D.SOME_THING="Thing"`.~~

~~Also, this is a bit verbose, expecially since the `-C` options only go to scikit-build in pyproject mode.~~
