### ISSUE TITLE
feat: force-include

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build-core#776]
We should support hatchling-style force-includes. See #669.

**Comment by henryiii** [comment]
I've played with this and I think it's going to be harder than I expected. I think we really need a set of three paths each, something like:

```toml
[[tool.scikit-build.force-include]]
source = "../other-folder"
sdist = "src/other-folder"
wheel = "other-folder"
```

We need a place to copy it into the SDist, and a place to copy it in the wheel.

In light of that, I might revisit the original table suggestion as a simpler intermediate option.
