### ISSUE TITLE
`cmake.prefix` entry-point can fail when it is pointing to a `MultiplexedPath`

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#885]
I am experimenting with building a compiled non-python project within scikit-build-core, and I've encountered an issue if you point the entry-point to a non-pythonic object, i.e.:
```toml
[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "CMake-Template"

[project.entry-points."cmake.prefix"]
CMakeTemplatePrefix = "cmake_template"

[tool.scikit-build]
wheel.install-dir = "cmake_template"
```

The verbose log shows:
```cmake
    set(CMAKE_PREFIX_PATH [===[MultiplexedPath('/home/lecris/CLionProjects/Template/venv/lib64/python3.12/site-packages/cmake_template');/home/lecris/CLionProjects/Template/venv/lib/python3.12/site-packages]===] CACHE PATH "" FORCE)
```

Probably should address in #880. But I need to debug more why did it even create `MultiplexedPath` in this case when I've installed it without editable or such.

---

Edit: So this is fun. It's a `MultiplexedPath` with a single item :shrug:
