### ISSUE TITLE
`wheel.packages` cannot point to a module?

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#888]
I've encountered this when trying to write a minimal test setup where I didn't care about placing everything in a proper package, but wanted to write them dirty as modules, i.e.:
```console
$ tree
.
├── CMakeLists.txt
├── hello.py
├── main.cpp -> ../main.cpp
└── pyproject.toml
```
```toml
[build-system]
requires = ["scikit-build-core", "main-project-that-i-am-testing-the-packaging-for"]
build-backend = "scikit_build_core.build"

[project]
name = "simple-test-for-the-CMake-find_package"
version = "0.0.0"

[project.scripts]
run_test = "hello:run"

[tool.scikit-build]
wheel.install-dir = "simple_test"
wheel.packages = ["hello"]
```

And in the test I want to simply run the executable. I would probably remove the `wheel.install-dir` so that it installs directly into `SKBUILD_SCRIPTS_DIR`, but just a weird setup where I got this to break :shrug:
