### ISSUE TITLE
`AssertionError:` "Editable installs cannot rebuild an absolute wheel.install-dir. Use an override to change if needed."

### ISSUE THREAD

**Issue by Jacobfaib** [scikit-build/scikit-build-core#909]
Given
```toml
[tool.scikit-build]
wheel.install-dir = "/data"
```
It is not possible to do editable installs:
```sh
$ pip install -e .
```
because `scikit_build.build.wheel.py::_make_editable()` throws.

Commenting out this check did not _seem_ to break anything immediately with the wheel, so perhaps this check can be moved to runtime install of install-time.
