### ISSUE TITLE
Building always defaults to using `Debug` mode

### ISSUE THREAD

**Issue by JackAshwell11** [scikit-build/scikit-build-core#947]
So this is my pyproject.toml:
```toml
[tool.scikit-build]
cmake.source-dir = "src/hades_extensions"

[[tool.scikit-build.overrides]]
if.platform-system = "^win32"
cmake.args = ["-GNinja", "-DDO_TESTS=OFF", "--preset WinRelease"]

[[tool.scikit-build.overrides]]
if.platform-system = "^linux"
cmake.args = ["-GNinja", "-DDO_TESTS=OFF", "--preset LinuxRelease"]
```
And the corresponding `CMakePresets.json`:
```json
{
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 22,
    "patch": 1
  },
  "configurePresets": [
    {
      "binaryDir": "${sourceDir}/build-debug",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Debug",
        "VCPKG_TARGET_TRIPLET": "x64-windows"
      },
      "description": "Debug build",
      "generator": "Ninja",
      "name": "WinDebug"
    },
    {
      "binaryDir": "${sourceDir}/build-release",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release",
        "ENABLE_COVERAGE": "OFF",
        "VCPKG_TARGET_TRIPLET": "x64-windows"
      },
      "description": "Release build",
      "generator": "Ninja",
      "name": "WinRelease"
    }
  ],
  "version": 3
}
```
When I build my project (even using `uv sync --reinstall` to rebuild all dependencies), it should build my C++ extension in release mode and install that, but it seems to always be using the debug mode creating a massive performance impact.

I've checked this by manually building the project through `cmake --preset WinRelease`, `cmake --build build-release`, and transferring the files over which seems to sort out the performance problem.

Any idea why this might be occurring and what I can do to fix it?
